### ISSUE TITLE
Missing data.json

### ISSUE THREAD

**Issue by aalee** [junzhli/purevpn_server_list_config_generator#1]
When run purevpn_openvpn_config_generator.py show me the next error:

> No such file or directory: 'templates\\data.json'

I need some to run?

**Comment by junzhli** [comment]
Maybe data.json is not created at runtime. Did you run this script with Internet connected?
Just be sure your computer running this can get access to PureVPN official site [link](https://support.purevpn.com/vpn-servers)

**Comment by junzhli** [comment]
> When run purevpn_openvpn_config_generator.py show me the next error:
> 
> > No such file or directory: 'templates\data.json'
> 
> I need some to run?

Maybe data.json is not created successfully at runtime. Did you run this script with Internet connected?
Just to be sure your computer running this can get access to PureVPN official site [link](https://support.purevpn.com/vpn-servers)

**Comment by aalee** [comment]
It's a problem with scrapy and Python 3, I created a new project based on you project and Python 3, I'll soon publish and i'll mention your project.

Thank you very much, It's a great work, helped me very much
